//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by superupd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SUPERUPD_DIALOG             102
#define IDD_REPORT_VIEWER               116
#define IDR_MAINFRAME                   128
#define IDD_STATUS                      129
#define IDC_DO_ROUTE                    1000
#define IDC_EPASS_BASEDIR               1001
#define IDC_SAVE_SETTINGS               1002
#define IDC_CLEAR_ALL                   1003
#define IDC_EPASS_SHAREDDIR             1004
#define IDC_STATUS                      1004
#define IDC_DO_MAINTENANCEMGR           1005
#define IDC_DO_ALPASS                   1032
#define IDC_ALPASS_BASEDIR              1033
#define IDC_DO_OHPASS                   1036
#define IDC_OHPASS_BASEDIR              1037
#define IDC_DO_ARPASS                   1038
#define IDC_ARPASS_BASEDIR              1039
#define IDC_DO_SDPASS                   1040
#define IDC_SDPASS_BASEDIR              1041
#define IDC_DO_CTPASS                   1050
#define IDC_CTPASS_BASEDIR              1051
#define IDC_DO_NEPASS                   1054
#define IDC_NEPASS_BASEDIR              1055
#define IDC_DO_OHEPASS                  1060
#define IDC_OHEPASS_BASEDIR             1061
#define IDC_DO_AREPASS                  1062
#define IDC_AREPASS_BASEDIR             1063
#define IDC_DO_SDEPASS                  1064
#define IDC_SDEPASS_BASEDIR             1065
#define IDC_DO_CTEPASS                  1066
#define IDC_CTEPASS_BASEDIR             1067
#define IDC_DO_WVEPASS                  1068
#define IDC_WVEPASS_BASEDIR             1069
#define IDC_DO_NEEPASS                  1070
#define IDC_NEEPASS_BASEDIR             1071
#define IDC_ROUTE_BASE_DIR              1072
#define IDC_WINSYSDIR                   1073
#define IDC_DO_ALDATA                   1074
#define IDC_DO_ARDATA                   1075
#define IDC_DO_CTDATA                   1076
#define IDC_DO_IADATA                   1077
#define IDC_DO_KYDATA                   1078
#define IDC_DO_NEDATA                   1079
#define IDC_DO_OHDATA                   1080
#define IDC_DO_SDDATA                   1081
#define IDC_DO_WIDATA                   1082
#define IDC_DO_WVDATA                   1083
#define IDC_DO_KYERM                    1084
#define IDC_KYERM_BASEDIR               1085
#define IDC_DO_OHERM                    1086
#define IDC_OHERM_BASEDIR               1087
#define IDC_DO_NEERM                    1088
#define IDC_TEXT                        1088
#define IDC_NEERM_BASEDIR               1089
#define IDC_DO_KYERM2                   1090
#define IDC_DO_QLDEPASS                 1091
#define IDC_DO_PASSDB                   1092
#define IDC_PASSDB_BASEDIR              1093
#define IDC_DO_RESTDB                   1094
#define IDC_RESTDB_BASEDIR              1095
#define IDC_DO_CTERM                    1096
#define IDC_CTERM_BASEDIR               1097
#define IDC_PRINT                       1098
#define IDC_DO_MULTISTATE               1098
#define IDC_DO_WVERM                    1099
#define IDC_WVERM_BASEDIR               1100
#define IDC_MULTISTATE_BASEDIR          1101
#define IDC_DO_WIEROUTE                 1102
#define IDC_WIEROUTE_BASEDIR            1103
#define IDC_DO_ALEPASS                  1104
#define IDC_ALEPASS_BASEDIR             1105
#define IDC_DO_VADATA                   1106
#define IDC_DO_VAERM                    1107
#define IDC_DO_ALERM                    1108
#define IDC_ALERM_BASEDIR               1109
#define IDC_DO_ARERM                    1110
#define IDC_ARERM_BASEDIR               1111
#define IDC_DO_MIDATA                   1112
#define IDC_DO_MIERM                    1113
#define IDC_MIERM_BASEDIR               1114
#define IDC_DO_GADATA                   1115
#define IDC_DO_CODATA                   1116
#define IDC_DO_ILDATA                   1117
#define IDC_DO_NJDATA                   1118
#define IDC_DO_NCDATA                   1119
#define IDC_DO_AZDATA                   1120
#define IDC_VAERM_BASEDIR               1121
#define IDC_DO_VAEROUTE                 1122
#define IDC_VAEROUTE_BASEDIR            1123
#define IDC_DO_IAEPASS                  1124
#define IDC_IAEPASS_BASEDIR             1125
#define IDC_DO_IAERM                    1126
#define IDC_IAERM_BASEDIR               1127
#define IDC_DO_MIEPASS                  1128
#define IDC_MIEPASS_BASEDIR             1129
#define IDC_DO_NJEPASS                  1130
#define IDC_NJEPASS_BASEDIR             1131
#define IDC_DO_NCERSTMGR                1132
#define IDC_NCERM_BASEDIR               1133
#define IDC_DO_NJERM                    1134
#define IDC_NJERM_BASEDIR               1135
#define IDC_DO_LADATA                   1136
#define IDC_DO_WAData                   1137
#define IDC_DO_KYEPASS                  1138
#define IDC_KYEPASS_BASEDIR             1139
#define IDC_DO_ORDATA                   1140
#define IDC_BAT_ONLY                    1141
#define IDC_UPDATE_FILE                 1142
#define IDC_LOCATION                    1143
#define IDC_DO_MDERSTMGR                1144
#define IDC_MDERM_BASEDIR               1145
#define IDC_DO_MDDATA                   1146
#define IDC_DO_WIERM                    1147
#define IDC_WIERM_BASEDIR               1148
#define IDC_DO_SDERM                    1149
#define IDC_SDERM_BASEDIR               1150
#define IDC_DO_AZEPASS                  1151
#define IDC_AZEPASS_BASEDIR             1152
#define IDC_DO_AZERM                    1153
#define IDC_AZERM_BASEDIR               1154
#define IDC_DO_MDEPASS                  1155
#define IDC_MDEPASS_BASEDIR             1156
#define IDC_DO_QLDDATA                  1157
#define IDC_DATA_LOCATION               1158
#define IDC_QLDEPASS_BASEDIR            1159
#define IDC_DO_QLDERM                   1160
#define IDC_QLDERM_BASEDIR              1161
#define IDC_DO_CT_ADDRESS               1162
#define IDC_DO_MD_ADDRESS               1163
#define IDC_DO_WI_ADDRESS               1164
#define IDC_DO_VA_ADDRESS               1165
#define IDC_DO_QLD_ADDRESS              1166
#define IDC_DO_NJ_ADDRESS               1167
#define IDC_DO_MODATA                   1168
#define IDC_DO_MOEPASS                  1170
#define IDC_MOEPASS_BASEDIR             1171
#define IDC_DO_MOERSTMGR                1172
#define IDC_MDERM_BASEDIR2              1173
#define IDC_MOERM_BASEDIR               1173

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
